// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var OnegraphAuth = require("onegraph-auth");

var appId = "b36150b7-ce64-4a6c-a2af-fbe50da58552";

var authConfig = {
  appId: appId,
  oneGraphOrigin: "https://serve.onegraph.io"
};

var auth = new OnegraphAuth.OneGraphAuth(authConfig);

exports.appId = appId;
exports.authConfig = authConfig;
exports.auth = auth;
/* auth Not a pure module */
