// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as OnegraphAuth from "onegraph-auth";

var isSsr = (typeof window === "undefined");

var appId = "f1b8d65a-c97c-43c3-ac72-9a289de3c257";

var oneGraphUrl = "https://serve.onegraph.com/graphql?app_id=" + (String(appId) + "");

var authConfig = {
  appId: appId,
  oneGraphOrigin: "https://serve.onegraph.com"
};

var auth = isSsr ? undefined : Caml_option.some(new OnegraphAuth.OneGraphAuth(authConfig));

export {
  isSsr ,
  appId ,
  oneGraphUrl ,
  authConfig ,
  auth ,
  
}
/* isSsr Not a pure module */
