// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var OnegraphAuth = require("onegraph-auth");

var appId = "f1b8d65a-c97c-43c3-ac72-9a289de3c257";

var authConfig = {
  appId: appId,
  oneGraphOrigin: "https://serve.onegraph.com"
};

var auth = new OnegraphAuth.OneGraphAuth(authConfig);

exports.appId = appId;
exports.authConfig = authConfig;
exports.auth = auth;
/* auth Not a pure module */
