// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function payload(jwt) {
  var pieces = jwt.split(".");
  var payload$1 = Caml_array.caml_array_get(pieces, 1);
  return JSON.parse(atob(payload$1));
}

function findGitHubLogin(jwt) {
  var __x = jwt.user;
  return Belt_Option.flatMap(__x, (function (user) {
                return user.gitHubLogin;
              }));
}

function avatarUrl(jwt) {
  var __x = jwt.user;
  return Belt_Option.flatMap(__x, (function (user) {
                return user.avatarUrl;
              }));
}

export {
  payload ,
  findGitHubLogin ,
  avatarUrl ,
  
}
/* No side effect */
