// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReasonRelay from "reason-relay/src/ReasonRelay.bs.js";

var Unions = { };

var Types = { };

var fragmentConverter = ({"__root":{"bio":{"n":""},"name":{"n":""}}});

function convertFragment(v) {
  return ReasonRelay._convertObj(v, fragmentConverter, /* () */0, undefined);
}

var Internal = {
  fragmentConverter: fragmentConverter,
  fragmentConverterMap: /* () */0,
  convertFragment: convertFragment
};

var Utils = { };

var node = ({
  "kind": "Fragment",
  "name": "RelayComponentTest_GitHubUser",
  "type": "GitHubUser",
  "metadata": null,
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "bio",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "avatarUrl",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "isHireable",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "name",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "login",
      "args": null,
      "storageKey": null
    }
  ]
});

export {
  Unions ,
  Types ,
  Internal ,
  Utils ,
  node ,
  
}
/* fragmentConverter Not a pure module */
