// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactMonacoEditor from "react-monaco-editor";
import * as ReactMonacoEditor1 from "react-monaco-editor1";

var Editor = {
  make: ReactMonacoEditor1.default
};

var DiffViewer = {
  make: ReactMonacoEditor.MonacoDiffEditor
};

export {
  Editor ,
  DiffViewer ,
  
}
/* Editor Not a pure module */
