// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useWindowSize(onResize) {
  var $$window$1 = window;
  var isClient = !($$window$1 == null);
  var getSize = function (param) {
    if ($$window$1 == null) {
      return ;
    } else {
      return {
              width: $$window$1.innerWidth,
              height: $$window$1.innerHeight
            };
    }
  };
  var match = React.useState((function () {
          return getSize(/* () */0);
        }));
  var setWindowSize = match[1];
  React.useEffect((function () {
          if (isClient && !($$window$1 == null)) {
            var handleResize = function (param) {
              return Curry._1(setWindowSize, (function (param) {
                            var size = getSize(/* () */0);
                            Curry._1(onResize, size);
                            return size;
                          }));
            };
            $$window$1.addEventListener("resize", handleResize);
            return (function (param) {
                      $$window$1.removeEventListener("resize", handleResize);
                      return /* () */0;
                    });
          }
          
        }), ([]));
  return match[0];
}

exports.useWindowSize = useWindowSize;
/* react Not a pure module */
