// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var make = React.lazy((function (param) {
        return import("react-monaco-editor");
      }));

var Lazy = {
  make: make
};

var Editor = {
  Lazy: Lazy
};

var make$1 = React.lazy((function (param) {
        return import("react-monaco-editor");
      }));

var Lazy$1 = {
  make: make$1
};

var DiffViewer = {
  Lazy: Lazy$1
};

export {
  Editor ,
  DiffViewer ,
  
}
/*  Not a pure module */
